name: Deploy Radico Dashboard to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Debug - List repository contents
        run: |
          echo "=== Repository root contents ==="
          ls -la
          echo "=== Check for app directory ==="
          if [ -d "app" ]; then
            echo "✅ app directory found!"
            ls -la app/
          else
            echo "❌ app directory NOT found!"
          fi
          echo "=== Check for pages directory ==="
          if [ -d "pages" ]; then
            echo "✅ pages directory found!"
            ls -la pages/
          else
            echo "❌ pages directory NOT found!"
          fi
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Install dependencies
        run: npm install
        
      - name: Build application
        run: npm run build
        env:
          NEXT_PUBLIC_GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          NEXT_PUBLIC_MASTER_SHEET_ID: 1pRz9CgOoamTrfpnmF-XuBCg9IZON9br5avgRlKYtxM
          NEXT_PUBLIC_VISIT_SHEET_ID: 1XG4c_Lrpk-YglTq3G3ZY9Qjt7wSnUq0UZWDSYT61eWt
          
      - name: Copy PWA file to output
        run: |
          echo "=== Copying PWA file ==="
          if [ -f "public/pwa.html" ]; then
            cp public/pwa.html ./out/pwa.html
            echo "✅ PWA file copied successfully!"
            echo "Files in out directory:"
            ls -la ./out/
          else
            echo "❌ PWA file not found in public/"
          fi
          
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
